export const DATA = [
  {
    key: "41",
    edad: 4,
    idCategoria: 1,
    title: "Día Noche",
    image: require("../assets/images/day-and-night.png"),
  },
  {
    key: "51",
    edad: 5,
    idCategoria: 1,
    title: "Día Tarde y Noche",
    image: require("../assets/images/sunsets.png"),
  },
  {
    key: "61",
    edad: 6,
    title: "Joven Viejo",
    idCategoria: 1,
    image: require("../assets/images/age-limit.png"),
  },
  {
    key: "42",
    edad: 4,
    title: "Alto Bajo",
    idCategoria: 2,
    image: require("../assets/images/height.png"),
  },
  {
    key: "52",
    edad: 5,
    title: "Largo Corto",
    idCategoria: 2,
    image: require("../assets/images/grandeYchico.png"),
  },
  {
    key: "62",
    edad: 6,
    title: "Grande Pequeño",
    idCategoria: 2,
    image: require("../assets/images/star-shape-big-and-small.png"),
  },
  {
    key: "43",
    edad: 4,
    title: "Colores",
    idCategoria: 3,
    image: require("../assets/images/rgb.png"),
  },
  {
    key: "53",
    edad: 5,
    title: "Colores",
    idCategoria: 3,
    image: require("../assets/images/color-palette.png"),
  },
  {
    key: "63",
    edad: 6,
    title: "Colores",
    idCategoria: 3,
    image: require("../assets/images/color-wheel.png"),
  },
  {
    key: "44",
    edad: 4,
    title: "Figuras Geométricas",
    idCategoria: 4,
    image: require("../assets/images/geometrical-shapes.png"),
  },
  {
    key: "54",
    edad: 5,
    title: "Figuras Geométricas",
    idCategoria: 4,
    image: require("../assets/images/geometrical-shapes (1).png"),
  },
  {
    key: "64",
    edad: 6,
    title: "Figuras Geométricas",
    idCategoria: 4,
    image: require("../assets/images/hexagons.png"),
  },
  {
    key: "45",
    edad: 4,
    title: "Reconocer hasta 5",
    idCategoria: 5,
    image: require("../assets/images/five.png"),
  },
  {
    key: "55",
    edad: 5,
    title: "Reconocer hasta 10",
    idCategoria: 5,
    image: require("../assets/images/10.png"),
  },
  {
    key: "65",
    edad: 6,
    title: "Más y menos que",
    idCategoria: 5,
    image: require("../assets/images/is-greater-than.png"),
  },
];

export const DatosCategoria = [
  {
    key: "1",
    title: "Nociones Temporales espaciales",
    image: require("../assets/images/3d-glasses.png"),
  },
  {
    key: "2",
    title: "Nociones de medida",
    image: require("../assets/images/boot.png"),
  },
  {
    key: "3",
    title: "Colores",
    image: require("../assets/images/flamingo.png"),
  },
  {
    key: "4",
    title: "Figuras Geométricas",
    image: require("../assets/images/game-controller.png"),
  },
  {
    key: "5",
    title: "Nociones de cantidad",
    image: require("../assets/images/coins.png"),
  },
];
